{% set name = "safe-mol" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/safe-mol-{{ version }}.tar.gz
  sha256: 907078f8e70c2ff9e436634cdd2a039446c75b7d6e1f4c1ce894734331ab935a

build:
  entry_points:
    - safe-train = safe.trainer.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=3.9
    - tqdm
    - loguru
    - typer
    - universal_pathlib
    - datamol
    - numpy
    - pytorch >=2.0
    - transformers
    - datasets
    - tokenizers
    - accelerate
    - evaluate
    - wandb
    - huggingface_hub

test:
  imports:
    - safe
  commands:
    - safe-train --help

about:
  home: https://github.com/datamol-io/safe
  summary: "Implementation of the 'Gotta be SAFE: a new framework for molecular design' paper"
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
    - maclandrol
