{% set name = "safe-mol" %}
{% set version = "0.1.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 235b7c84bcfe8e80c602387bade3a0d9183d0b0a1b73e07234d8ee83f7b1d019

build:
  entry_points:
    - safe-train = safe.trainer.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - tqdm
    - loguru
    - typer
    - universal_pathlib
    - datamol
    - rdkit
    - numpy
    - pytorch >=2.0
    - transformers >=4.30,<5
    - datasets
    - tokenizers
    - accelerate
    - evaluate
    - wandb
    - huggingface_hub <1

test:
  requires:
    - python {{ python_min }}
  imports:
    - safe
  commands:
    - safe-train --help

about:
  home: https://github.com/datamol-io/safe
  summary: "A single model for all your molecular design tasks"
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maclandrol
