{% set name = "safe-mol" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/safe-mol-{{ version }}.tar.gz
  sha256: a52dfb63760d01b5dd9410da215f0f00c6b4dd04c61c684276bf1284b1080a08

build:
  entry_points:
    - safe-train = safe.trainer.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=3.9
    - tqdm
    - loguru
    - typer
    - universal_pathlib
    - datamol
    - numpy
    - pytorch >=2.0
    - transformers
    - datasets
    - tokenizers
    - accelerate
    - evaluate
    - wandb
    - huggingface_hub

test:
  imports:
    - safe
  commands:
    - safe-train --help

about:
  home: https://github.com/datamol-io/safe
  summary: "A single model for all your molecular design tasks"
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
    - maclandrol
