{% set name = "safe-mol" %}
{% set version = "0.1.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 9c8ccf0f13e94a28dcf8c0d77f8c3954d2bc805f58b70d8d645055d3bc1b8f9f

build:
  entry_points:
    - safe-train = safe.trainer.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=3.9
    - tqdm
    - loguru
    - typer
    - universal_pathlib
    - datamol
    - numpy
    - pytorch >=2.0
    - transformers >=4.30
    - datasets
    - tokenizers
    - accelerate
    - evaluate
    - wandb
    - huggingface_hub

test:
  imports:
    - safe
  commands:
    - safe-train --help

about:
  home: https://github.com/datamol-io/safe
  summary: "A single model for all your molecular design tasks"
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maclandrol
